apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopnow-backend
  template:
    metadata:
      labels:
        app: shopnow-backend
    spec:
      containers:
      - name: backend
        image: 975050024946.dkr.ecr.us-east-1.amazonaws.com/shopnow-backend/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/shopnow"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: shopnow-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
