apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopnow-frontend
  template:
    metadata:
      labels:
        app: shopnow-frontend
    spec:
      containers:
      - name: frontend
        image: 975050024946.dkr.ecr.us-east-1.amazonaws.com/shopnow-frontend/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://backend-service:5000"
        resources:
          requests:
<<<<<<< HEAD
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
=======
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
>>>>>>> 11232de (Initial commit - shopNow project)
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: shopnow-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnow-ingress
spec:
  rules:
  - host: shopnow.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000
